[package]
name = "rusjure_compiler"
version = "0.0.0"
authors = ["Artify"]
edition = '2021'
repository = "https://github.com/ArtifyCZ/rusjure"

[dependencies]
rusjure_lst = { version = "0.0.0", path = "../lst" }
rusjure_stdlib = { version = "0.0.0", path = "../stdlib" }

inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
