[package]
name = "rusjure_compiler"
version = "0.0.0"
authors = ["Artify"]
edition = '2021'
repository = "https://github.com/ArtifyCZ/rusjure"

[dependencies]
rusjure_ast = { version = "0.0.0", path = "../ast" }

llvm-safely = { version = "0.0.0", path = "../llvm" }
