[package]
name = "rusjure_compiler"
version = "0.0.0"
authors = ["Artify"]
edition = '2021'
repository = "https://github.com/ArtifyCZ/rusjure"

[dependencies]
rusjure_ast = { version = "0.0.0", path = "../ast" }

inkwell = "0.1.0-beta.5"
