[package]
name = "rusjure_compiler"
version = "0.0.0"
authors = ["Artify"]
edition = '2021'
repository = "https://github.com/ArtifyCZ/rusjure"

[dependencies]
rusjure_lst = { version = "0.0.0", path = "../lst" }
rusjure_stdlib = { version = "0.0.0", path = "../stdlib" }

inkwell = { version = "0.1.0-beta.5", features = ["llvm15-0"] }
